app_id: 8A11A9CC-4D46-4828-AFED-1BC7F19DF840
publisher: PCL Log Viewer
publisher_url: https://github.com/Ignis-Studio/PCL-Log-Viewer
display_name: PCL Log Viewer
executable_name: pcl_log_viewer_x86-64.exe
output_base_file_name: pcl_log_viewer_x86-64.exe
create_desktop_icon: true
install_dir_name: "{autopf64}\\PCL Log Viewer"
setup_icon_file: ..\..\windows\runner\resources\app_icon.ico
locales:
  - ar
  - en
  - fa
  - ru
  - pt
  - tr
script_template: inno_setup.sas